---

- name: LDAP Auth with automatic registration
  theforeman.foreman.auth_source_ldap:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: lab-ldap
    host: 172.16.203.20
    port: 389
    tls: false
    onthefly_register: true
    usergroup_sync: true
    account: ""
    account_password: ""
    base_dn: ou=Users,dc=lab,dc=loxda,dc=net
    groups_base: ou=ForemanGroups,dc=lab,dc=loxda,dc=net
    server_type: posix
    attr_login: uid
    attr_firstname: givenName
    attr_lastname: sn
    attr_mail: mail
    ldap_filter: "" # (&(objectclass=posixaccount)(uid=%s))
    locations: LAB
    organizations: LAB
    state: present
