---

- name: "Create domains"
  theforeman.foreman.domain:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
    state: present
  loop: "{{ foreman_domain }}"
  delegate_to: localhost
