---

- name: "Create subnets"
  theforeman.foreman.subnet:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
    ipam: "{{ item.ipam | default(omit) }}"
    gateway: "{{ item.gateway }}"
    dns_primary: "{{ item.dns_primary }}"
    dns_secondary: "{{ item.dns_secondary }}"
    from_ip: "{{ item.from_ip }}"
    to_ip: "{{ item.to_ip }}"
    boot_mode: "{{ item.boot_mode | default(omit) }}"
    dhcp_proxy: "{{ item.dhcp_proxy | default(omit) }}"
    tftp_proxy: "{{ item.tftp_proxy | default(omit) }}"
    httpboot_proxy: "{{ item.httpboot_proxy | default(omit) }}"
    template_proxy: "{{ item.template_proxy | default(omit) }}"
    discovery_proxy: "{{ item.discovery_proxy | default(omit) }}"
    remote_execution_proxies: "{{ item.remote_execution_proxies | default(omit) }}"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    domains: "{{ item.domains }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
    state: present
  loop: "{{ foreman_subnets }}"
  delegate_to: localhost
