---

- name: Create compute resources
  theforeman.foreman.compute_resource:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    provider: "{{ item.provider }}"
    provider_params: "{{ item.provider_params }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
    state: present
  loop: "{{ foreman_compute_resources }}"
  delegate_to: localhost
