---

- name: Create compute image
  theforeman.foreman.image:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    image_uuid: "{{ item.image_uuid }}"
    image_username: "{{ item.image_username }}"
    operatingsystem: "{{ item.operatingsystem }}"
    compute_resource: "{{ item.compute_resource }}"
    architecture: "{{ item.architecture }}"
    user_data: "{{ item.user_data }}"
    state: present
  loop: "{{ foreman_compute_image }}"
  delegate_to: localhost
