---

- name: "Create Hostgroup"
  theforeman.foreman.hostgroup:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    parent: "{{ item.parent }}"
    organizations: "{{ item.organizations }}"
    locations: "{{ item.locations }}"
    parameters: "{{ item.parameters|default(omit) }}"
    puppetclasses: "{{ item.puppetclasses|default(omit) }}"
    ansible_roles: "{{ item.ansible_roles|default(omit) }}"
    environment: "{{ item.environment|default(omit) }}"
    compute_resource: "{{ item.compute_resource|default(omit) }}"
    compute_profile: "{{ item.compute_profile|default(omit) }}"
    architecture: "{{ item.architecture|default(omit) }}"
    operatingsystem: "{{ item.operatingsystem|default(omit) }}"
    medium: "{{ item.medium|default(omit) }}"
    ptable: "{{ item.ptable|default(omit) }}"
    pxe_loader: "{{ item.pxe_loader|default(omit) }}"
    state: present
  loop: "{{ foreman_hostgroup }}"
  delegate_to: localhost
