---

- name: Set smart_class_parameter
  theforeman.foreman.smart_class_parameter:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    puppetclass_name: "{{ item.name }}"
    parameter: "{{ item.parameter }}"
    parameter_type: "{{ item.parameter_type | default(omit) }}"
    override: "{{ item.override | default(omit) }}"
    omit: "{{ item.omit | default(omit) }}"
    override_value_order: "{{ item.override_value_order | default(omit) }}"
    required: "{{ item.required | default(omit) }}"
    default_value: "{{ item.default_value | default(omit) }}"
    override_values: "{{ item.override_values | default(omit) }}"
    state: "{{ item.state }}"
  loop: "{{ foreman_smart_class_parameter }}"
  delegate_to: localhost
