---

- name: Set user group
  theforeman.foreman.usergroup:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    admin: "{{ item.admin }}"
    roles: "{{ item.roles }}"
    state: present
  loop: "{{ foreman_usergroup }}"
  delegate_to: localhost

- name: Set external user group
  theforeman.foreman.external_usergroup:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    auth_source: "{{ item.auth_source }}"
    usergroup: "{{ item.usergroup }}"
    state: present
  loop: "{{ foreman_external_usergroup }}"
  delegate_to: localhost
