---

# Windows templates

- name: "Create a Provisioning Template from a file"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    file_name: "{{ role_path }}/files/{{ item.file_name }}"
    name: "{{ item.name }}"
    kind: "{{ item.kind }}"
    state: "{{ item.state }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
  loop: "{{ foreman_provisioning_template }}"
  when: "'Windows' in item.name"
  delegate_to: localhost

# Assign default templates to OS Windows

- name: "Assign OS: Windows all versions -> PXELinux chain iPXE"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "PXELinux chain iPXE"
    operatingsystems:
      - "{{ item.description }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"
  when: "'Windows' in item.description"
  delegate_to: localhost

- name: "Assign OS: Windows all versions -> Windows default iPXE httpboot imgfree"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "Windows default iPXE httpboot imgfree"
    operatingsystems:
      - "{{ item.description }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"
  when: "'Windows' in item.description"
  delegate_to: localhost

- name: "Assign OS: Windows all versions -> Windows default provision"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "Windows default provision"
    operatingsystems:
      - "{{ item.description }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"
  when: "'Windows' in item.description"
  delegate_to: localhost

- name: "Assign OS: Windows all versions -> Windows peSetup.cmd noproxy"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "Windows peSetup.cmd noproxy"
    operatingsystems:
      - "{{ item.description }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"
  when: "'Windows' in item.description"
  delegate_to: localhost

- name: "Assign OS: Windows all versions -> Windows default finish FR"
  theforeman.foreman.provisioning_template:
    server_url: "{{ foreman_url_app }}"
    username: "{{ foreman_admin_username }}"
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    name: "Windows default finish FR"
    operatingsystems:
      - "{{ item.description }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"
  when: "'Windows' in item.description"
  delegate_to: localhost

# Trigger handlers to assign OS default templates

- name: "Trigger OS Assign Provisioning templates"
  ansible.builtin.command: /bin/true
  changed_when: true
  notify:
    - "Assign Provisioning templates to OS Windows"
    - "Set Windows default Provisioning templates to OS finish"
    - "Set Windows default Provisioning templates to OS provision"
    - "Set Windows default Provisioning templates to OS PXELinux"
    - "Set Windows default Provisioning templates to OS iPXE"
    - "Set Windows default Provisioning templates to OS script"
  delegate_to: localhost
